#cloud-config
apt:
  sources:
    docker:
      keyid: '9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88'
      source: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable'
    dokku:
      keyid: '0027 A6FC E4DE B304 104D 2D13 F1FF 6851 288B 3315'
      source: 'deb https://packagecloud.io/dokku/dokku/ubuntu/ $RELEASE main'
  debconf_selections:
    dokku: |
      dokku dokku/web_config boolean false
      dokku dokku/hostname string gophers.id
      dokku dokku/skip_key_file boolean true
package_update: true
package_upgrade: true
packages:
  - ufw
  - build-essential
  - dnsutils
  - docker-ce
  - git
  - dokku
runcmd:
  - ufw allow ssh
  - ufw allow http
  - ufw allow https
  - ufw enable
  - adduser ubuntu docker
  - sed -i -e 's/AllowUsers.*/AllowUsers ubuntu dokku/' /etc/ssh/sshd_config
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
  - chmod +x /usr/bin/docker-compose
  - dokku plugin:install-dependencies --core
  - dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git
  - dokku apps:create gophers-web
  - mkdir -p /var/lib/dokku/data/storage/gophers-web
  - chown -R 32767:32767 /var/lib/dokku/data/storage/gophers-web
  - dokku storage:mount gophers-web /var/lib/dokku/data/storage/gophers-web:/storage
  - dokku docker-options:add gophers-web build "-v /var/lib/dokku/data/storage/gophers-web:/storage"
  - dokku domains:add gophers-web gophers.id
  - dokku config:set gophers-web APP_CONFIG=W3J1bnRpbWVdCmVudmlyb25tZW50PSIkRU5WfHxwcm9kdWN0aW9uIgpbc2VydmVyXQpwb3J0PSIkUE9SVHx8MzAwMCIKY3NyZnRva2VuPSIkQ1NSRlRPS0VOIgpbZ29vZ2xlXQptYXBzdG9rZW49IiRNQVBTVE9LRU4iCg==
  - dokku config:set gophers-web ENV=production
  - dokku domains:set gophers-web gophers.id www.gophers.id
  - dokku domains:enable gophers-web
  - dokku config:set --no-restart gophers-web DOKKU_LETSENCRYPT_EMAIL=admin@gophers.id
  - dokku letsencrypt gophers-web
  - dokku letsencrypt:cron-job --add
  - i=0; cat /home/ubuntu/.ssh/authorized_keys|(while read line; do ((i=i+1)); echo "$line"|dokku ssh-keys:add $(echo "$line"|awk '{print $3}'|tr '@' '-'); done)
  - mkdir -p /home/ubuntu/src
  - git clone https://github.com/kenshaw/shell-config.git /home/ubuntu/src/shell-config
  - chown ubuntu:ubuntu -R /home/ubuntu
  - su ubuntu -c 'rm ~/.bashrc && ~/src/shell-config/setup.sh'
  - GOCACHE=/tmp/gobuild /home/ubuntu/src/shell-config/scripts/go-setup.sh -u -c -f
power_state:
  mode: reboot
