[metadata.heroku]
  root-package = "gophers.id/gophers-web"
  go-version = "go1.9.2"
  ensure = "false"
  install = ["."]

[[constraint]]
  branch = "master"
  name = "github.com/golang/gddo"

[[constraint]]
  name = "github.com/gorilla/csrf"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/kenshaw/glogrus2"

[[constraint]]
  branch = "master"
  name = "github.com/kenshaw/gojiid"

[[constraint]]
  branch = "master"
  name = "github.com/knq/envcfg"

[[constraint]]
  branch = "master"
  name = "github.com/knq/wutil"

[[constraint]]
  name = "github.com/leonelquinteros/gotext"
  version = "1.2.4"

[[constraint]]
  name = "github.com/oschwald/maxminddb-golang"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/tylerb/graceful"
  version = "1.2.15"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[constraint]]
  name = "github.com/valyala/quicktemplate"
  version = "20160617.0.0"

[[constraint]]
  name = "goji.io"
  version = "2.0.0"
